# Generated by Django 3.0.7 on 2020-07-27 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exlog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
