# Generated by Django 3.0.8 on 2020-07-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exlog_app', '0003_auto_20200728_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_weight',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='num_reps',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='num_sets',
            field=models.PositiveIntegerField(),
        ),
    ]
