# Generated by Django 3.0.7 on 2020-06-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('group', models.CharField(max_length=100)),
                ('group_code', models.IntegerField()),
                ('description', models.TextField()),
                ('image_link', models.TextField()),
            ],
        ),
    ]
