<<<<<<< HEAD
# Generated by Django 3.0.7 on 2020-06-22 20:34

from django.db import migrations, models
=======
# Generated by Django 3.0.7 on 2020-06-20 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 06c1cd496f40eb88f32564cb134a2bf87998c98d


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 06c1cd496f40eb88f32564cb134a2bf87998c98d
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('group', models.CharField(max_length=100)),
                ('group_code', models.IntegerField()),
                ('description', models.TextField()),
                ('image_link', models.TextField()),
=======
            name='WeightLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('weight', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 06c1cd496f40eb88f32564cb134a2bf87998c98d
            ],
        ),
    ]
