# Generated by Django 3.0.7 on 2020-06-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='code',
        ),
    ]
