# Generated by Django 3.0.7 on 2020-07-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_exercise_food_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='ex_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
