# Generated by Django 3.0.7 on 2020-07-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_exercise_ex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_entry',
            name='calories',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='food_entry',
            name='description',
            field=models.CharField(max_length=40),
        ),
    ]
