# Generated by Django 3.0.7 on 2020-07-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200729_0228'),
        ('app', '0004_auto_20200730_0155'),
    ]

    operations = [
    ]
