# Generated by Django 3.0.7 on 2020-07-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20200730_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_entry',
            name='description',
            field=models.CharField(max_length=31),
        ),
    ]
